### ISSUE TITLE
mouse modes

### ISSUE THREAD

**Issue by ramagottfried** [ramagottfried/symbolist#2]
currently I started making an "edit mode" separate from "selection mode", but I think it's too complicated the way it's setup right now.

the way illustrator, inkscape and omnigraffle are designed is to have a "selection and transform mode" separate from the different draw modes, so probably we should do that also.

for example:
- mode 1: **edit** -- select, move, scale, rotate, group selected symbols (double clicking a group in edit mode opens the group and allows editing individual components?)
- mode 2: **path** -- add points to path, edit bezier curve handles
- mode 3: **circle** -- draw circle path, edit curve handles

**Comment by ramagottfried** [comment]
possibly do like illustrator and have two types of edit, one to transform move/scale/resize, and one to edit the path handles (cmd-click)

**Comment by ramagottfried** [comment]
as per our discussion earlier, the new plan is to have a default `edit` mouse mode -- then you hold cmd down to enter `draw` mode.  you can type [c] or [p] to set the shape type for draw mode.

**Comment by ramagottfried** [comment]
then later in `edit` mode, the type of editing can be contextual according to what kind of symbol it is.

**Comment by j-bresson** [comment]
_type [c] or [p] to set the shape type for draw mode._
=> I think this would rather depend on which button is pushed on the side palette ?

**Comment by j-bresson** [comment]
Commit: 19a6b342c0637285653b70973e19ec4005ec314c

Current situation : the UI mode can be only one of "draw" or "edit". 
This mode depends on whether or not some given modifier key(s) (cmd, shift, etc.) are down.

Then, which shape/symbol is currently concerned by the draw mode depends on the palette selection. I have left the [p] and [c] key events for the moment but they are just shortcuts to the palette functions.

+Note I don't think the draw-type can be an enum since it is likely to change dynamically along with the user defining / deleting symbol templates. This is just replaced by an integer for now : position of the currently active item of the palette.

**Comment by j-bresson** [comment]
Update

- **draw_mode** determines we are in a state of "free drawing" (free_draw) or copying a template symbol from the palette (from_template). This state is set by clicking or actions on the Palette.

- **mouse_mode** determines whether we are drawing (_draw_) or not (_selection_). 
It is set my the modifierKeysChanged callback.
It is used in several mouseDown/Up/Drag etc. 
(could be replaced by a simple test on this modifier)
